apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: rag-system # rag-system namespace'ine kur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          limits:
            # === DİKKAT! ===
            # WSL2 + k3d ortamında GPU device discovery sorunu var.
            # GPU talep etmeden çalıştırıyoruz. Ollama otomatik olarak GPU'yu tespit edecek.
            # GPU kullanılamıyorsa CPU modunda çalışacak (yavaş ama işlevsel).
            # nvidia.com/gpu: 1  # Şimdilik devre dışı
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
        # Modeli ilk açılışta çekmesi için:
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ollama pull qwen"]
      volumes:
      - name: dev
        hostPath:
          path: /dev
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: rag-system
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434