apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: rag-system # rag-system namespace'ine kur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      runtimeClassName: nvidia
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ollama pull qwen"]
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: rag-system
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434