apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/peler1nl1kelt0s/rag-system-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "0.5"
        env:
        - name: QDRANT_URL
          value: "http://qdrant-service.rag-system.svc.cluster.local:6333"
        - name: OLLAMA_URL
          value: "http://ollama-service.rag-system.svc.cluster.local:11434"
        - name: MODEL_NAME
          value: "qwen"
        - name: COLLECTION_NAME
          value: "apache_docs"
        - name: DATA_PATH
          value: "/data/"
        - name: DEBUG_MODE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
  namespace: rag-system
spec:
  type: ClusterIP
  selector:
    app: rag-backend
  ports:
  - port: 8000
    targetPort: 8000