apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubuntu-rag-sistemi
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/peler1nl1kelt0s/rag-system.git
    targetRevision: HEAD
    path: manifests
    # Private repo için authentication gerekli
    # Public repo için authentication gerekmez
  
  destination:
    server: https://kubernetes.default.svc
    namespace: rag-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true